In [8]:
import requests
import pandas as pd

def fetch_vid(page):
    url = f'https://api.socialverseapp.com/feed?page={page}'
    response = requests.get(url)
    return response.json()

video_data = fetch_vid(1)

videos = video_data['posts']

video_df = pd.json_normalize(videos)

video_df.head()

,id,slug,title,identifier,comment_count,upvote_count,view_count,exit_count,rating_count,average_rating,...,picture_url,category.id,category.name,category.count,category.description,category.image_url,baseToken.address,baseToken.name,baseToken.symbol,baseToken.image_url
0,1202,fd7077974fcb7be24d83b05e18843ddb30f64ac3,The Higher Self Podcast + TAG your personal he...,1aON1eV,0,0,1,441,0,95,...,https://assets.socialverseapp.com/profile/kinh...,2,Vible,486,All the best vibes!,https://assets.socialverseapp.com/categories/a...,,,,
1,1198,19ee6d8c100f305f5adbb8be3f230faecc638b3d,‚ÄúThat‚Äôs not pride‚Ä¶‚Äù ü§ç - Jordan Peterson - #rea...,ytkXm9g,0,0,4,455,2,11,...,https://assets.socialverseapp.com/profile/2.png,2,Vible,486,All the best vibes!,https://assets.socialverseapp.com/categories/a...,,,,
2,1196,98d3a3a36536df8a0e0c9944cf06c16066988848,This hits different as a parent‚Ä¶ #dailymotivat...,82T9MUh,0,1,3,481,0,0,...,https://assets.socialverseapp.com/profile/2.png,2,Vible,486,All the best vibes!,https://assets.socialverseapp.com/categories/a...,,,,
3,1195,a9868532b4b975ee1fa00609b0e923ab0ee9ba19,They are never going to be able to find anyone...,BExS9nU,0,0,3,230,0,0,...,https://assets.socialverseapp.com/profile/kinh...,2,Vible,486,All the best vibes!,https://assets.socialverseapp.com/categories/a...,,,,
4,1194,23e30acd0710b702881ebcb386e6e254414cc831,‚ÄúIf a girl really likes you‚Ä¶‚Äù ‚ù§Ô∏è_ü©π - Justin Wa...,pVxAh3Q,0,0,2,340,0,0,...,https://assets.socialverseapp.com/profile/kinh...,2,Vible,486,All the best vibes!,https://assets.socialverseapp.com/categories/a...,,,,

In [10]:
# Dummy user dataset
user_data = [
     {"user_id": 1, "watch_history": [1202, 1198], "language": "English", "location": "USA"},
    {"user_id": 2, "watch_history": [1196, 1195], "language": "Spanish", "location": "Mexico"},
    {"user_id": 3, "watch_history": [1194, 1202], "language": "English", "location": "Canada"},
    {"user_id": 4, "watch_history": [1198, 1196], "language": "French", "location": "France"},
    {"user_id": 5, "watch_history": [1195, 1194], "language": "English", "location": "UK"},
    {"user_id": 6, "watch_history": [1202, 1195], "language": "Spanish", "location": "Spain"},
    {"user_id": 7, "watch_history": [1198, 1202], "language": "English", "location": "Australia"},
    {"user_id": 8, "watch_history": [1196, 1194], "language": "German", "location": "Germany"},
    {"user_id": 9, "watch_history": [1202, 1198], "language": "English", "location": "India"},
    {"user_id": 10, "watch_history": [1195, 1196], "language": "Italian", "location": "Italy"},
    {"user_id": 11, "watch_history": [1194, 1202], "language": "Portuguese", "location": "Brazil"},
    {"user_id": 12, "watch_history": [1198, 1195], "language": "English", "location": "South Africa"},
    {"user_id": 13, "watch_history": [1202, 1194], "language": "Dutch", "location": "Netherlands"},
    {"user_id": 14, "watch_history": [1196, 1198], "language": "Japanese", "location": "Japan"},
    {"user_id": 15, "watch_history": [1195, 1202], "language": "Korean", "location": "South Korea"},
    {"user_id": 16, "watch_history": [1194, 1196], "language": "Russian", "location": "Russia"},
    {"user_id": 17, "watch_history": [1202, 1198], "language": "Chinese", "location": "China"},
    {"user_id": 18, "watch_history": [1195, 1194], "language": "Arabic", "location": "Saudi Arabia"},
    {"user_id": 19, "watch_history": [1198, 1196], "language": "English", "location": "New Zealand"},
    {"user_id": 20, "watch_history": [1202, 1195], "language": "French", "location": "Belgium"},
    {"user_id": 21, "watch_history": [1194, 1198], "language": "Hindi", "location": "India"},
    {"user_id": 22, "watch_history": [1196, 1202], "language": "Turkish", "location": "Turkey"},
    {"user_id": 23, "watch_history": [1195, 1194], "language": "English", "location": "Ireland"},
    {"user_id": 24, "watch_history": [1198, 1202], "language": "Swedish", "location": "Sweden"},
    {"user_id": 25, "watch_history": [1196, 1195], "language": "English", "location": "Singapore"},
    {"user_id": 26, "watch_history": [1202, 1194], "language": "English", "location": "Nigeria"},
    {"user_id": 27, "watch_history": [1198, 1196], "language": "French", "location": "Canada"},
    {"user_id": 28, "watch_history": [1195, 1202], "language": "Spanish", "location": "Argentina"},
    {"user_id": 29, "watch_history": [1194, 1198], "language": "English", "location": "Kenya"},
    {"user_id": 30, "watch_history": [1202, 1195], "language": "German", "location": "Austria"},

]

user_df = pd.DataFrame(user_data)

# Display the user DataFrame
user_df.head()

   user_id watch_history language location
0        1  [1202, 1198]  English      USA
1        2  [1196, 1195]  Spanish   Mexico

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Combine relevant text features for similarity (title + category name)
video_df['combined_features'] = video_df['title'] + ' ' + video_df['category.name']

# Create the TF-IDF matrix
tfidf_vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf_vectorizer.fit_transform(video_df['combined_features'])

# Compute cosine similarity between all videos
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# Display the cosine similarity matrix
cosine_sim[:5, :5]

array([[1.        , 0.02144721, 0.02560113, 0.02560113, 0.01825173],
       [0.02144721, 1.        , 0.03440403, 0.03440403, 0.09484187],
       [0.02560113, 0.03440403, 1.        , 0.27652741, 0.02927808],
       [0.02560113, 0.03440403, 0.27652741, 1.        , 0.02927808],
       [0.01825173, 0.09484187, 0.02927808, 0.02927808, 1.        ]])

In [12]:
def get_recommendations(user, video_df, cosine_sim):
    # Find the indices of the videos the user has watched
    watched_video_indices = [video_df[video_df['id'] == vid].index[0] for vid in user['watch_history']]
    
    # Calculate the mean similarity score of all videos against the watched videos
    similarity_scores = cosine_sim[watched_video_indices].mean(axis=0)
    
    # Sort videos by similarity score
    similar_videos_indices = similarity_scores.argsort()[::-1]
    
    # Recommend the top 5 most similar videos that the user hasn't watched yet
    recommendations = video_df.iloc[similar_videos_indices].head(10)
    recommendations = recommendations[~recommendations['id'].isin(user['watch_history'])]
    
    return recommendations[['id', 'title', 'category.name', 'view_count', 'average_rating']]

# Example: Get recommendations for User 1
recommendations_for_user_1 = get_recommendations(user_df.iloc[0], video_df, cosine_sim)
recommendations_for_user_1

,id,title,category.name,view_count,average_rating
4,1194,‚ÄúIf a girl really likes you‚Ä¶‚Äù ‚ù§Ô∏è_ü©π - Justin Wa...,Vible,2,0
3,1195,They are never going to be able to find anyone...,Vible,3,0
2,1196,This hits different as a parent‚Ä¶ #dailymotivat...,Vible,3,0

In [13]:
interaction_matrix = pd.DataFrame(0, index=user_df['user_id'], columns=video_df['id'])

for index, user in user_df.iterrows():
    interaction_matrix.loc[user['user_id'], user['watch_history']] = 1

interaction_matrix.head()

id       1202  1198  1196  1195  1194
user_id
1           1     1     0     0     0
2           0     0     1     1     0

In [14]:
from sklearn.neighbors import NearestNeighbors

model_knn = NearestNeighbors(metric='cosine', algorithm='brute')
model_knn.fit(interaction_matrix)


distances, indices = model_knn.kneighbors(interaction_matrix, n_neighbors=2)


def collaborative_filtering_recommendation(user_id, interaction_matrix, video_df, n_recommendations=5):
    similar_users = indices[user_id]
    similar_users_videos = interaction_matrix.iloc[similar_users].sum(axis=0)
    recommended_videos = similar_users_videos.sort_values(ascending=False).head(n_recommendations)
    return video_df[video_df['id'].isin(recommended_videos.index)][['id', 'title', 'category.name']]


collaborative_recommendations = collaborative_filtering_recommendation(0, interaction_matrix, video_df)
collaborative_recommendations

     id                                              title category.name
0  1202  The Higher Self Podcast + TAG your personal he...         Vible
1  1198  ‚ÄúThat‚Äôs not pride‚Ä¶‚Äù ü§ç - Jordan Peterson - #rea...         Vible
2  1196  This hits different as a parent‚Ä¶ #dailymotivat...         Vible
3  1195  They are never going to be able to find anyone...         Vible
4  1194  ‚ÄúIf a girl really likes you‚Ä¶‚Äù ‚ù§Ô∏è_ü©π - Justin Wa...         Vible